using UnityEngine;


namespace CharacterCompositor
{
    /// <summary>
    /// Instance of IMixTexture generated by the scriptable object: EyeMixTextures
    /// </summary>
    class EyeMixTexture : IMixTexture
    {
        private readonly Texture2D _texture;
        private readonly EyeMixTextureReferences _references;
        private readonly EyeIndividualMixTextureReferences _individualReferences;
        private readonly bool _isLeft;

        public EyeMixTexture(Texture2D texture, EyeMixTextureReferences references, EyeIndividualMixTextureReferences individualReferences, bool isLeft)
        {
            _texture = texture;
            _references = references;
            _individualReferences = individualReferences;
            _isLeft = isLeft;
        }

        public ColorGroup DefaultColorGroup => _individualReferences.DefaultColorGroup;

        public Color ContrastMidpointColor => _individualReferences.ContrastMidpointColor;

        public MaterialDescription TargetMaterialDescription => _isLeft ? _references.LeftMaterialDescription : _references.RightMaterialDescription;

        public Texture2D Shading => _texture;

        public Texture2D Mask => null;

        public string name => _texture.name;

        public bool Sortable => false;

        public TargetMaterialTexture TargetMaterialTexture => _individualReferences.TargetMaterialTexture;
    }
}
