using UnityEngine;


namespace CharacterCompositor
{
    /// <summary>
    /// Instance of IMixTexture generated by the scriptable object: EyeMixTextures
    /// </summary>
    class EyeMixTexture : IMixTexture
    {
        private readonly IEyeMixTextures _textures;
        private readonly EyeMixTextureReferences _references;
        private readonly bool _isLeft;
        private readonly bool _isFill;

        public EyeMixTexture(IEyeMixTextures textures, EyeMixTextureReferences references, bool isLeft, bool isFill)
        {
            _textures = textures;
            _references = references;
            _isLeft = isLeft;
            _isFill = isFill;
        }

        public ColorGroup DefaultColorGroup => _isFill ? _references.Fill.DefaultColorGroup : _references.Eyelid.DefaultColorGroup;

        public Color ContrastMidpointColor => _isFill ? _references.Fill.ContrastMidpointColor : _references.Eyelid.ContrastMidpointColor;

        public MaterialDescription TargetMaterialDescription => _isLeft ? _references.LeftMaterialDescription : _references.RightMaterialDescription;

        public Texture2D Shading => _isFill ? _textures.Fill : _textures.Eyelid;

        public Texture2D Mask => null;

        public string name => _textures.name + "_" + (_isLeft ? "left" : "right") + (_isFill ? "fill" : "eyelid");

        public bool Sortable => false;
    }
}
