using Character.Data;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;


namespace Character.Compositor
{
	/// <summary>
	/// Instance of IMixTexture generated by the scriptable object: EyeMixTextures
	/// </summary>
	class EyeMixTexture : IMixTexture
	{
		private readonly Texture2D _texture;
		private readonly EyeMixTextureReferences _references;
		private readonly EyeIndividualMixTextureReferences _individualReferences;
		private readonly bool _isLeft;

		public EyeMixTexture(Texture2D texture, EyeMixTextureReferences references, EyeIndividualMixTextureReferences individualReferences, bool isLeft)
		{
			_texture = texture;
			_references = references;
			_individualReferences = individualReferences;
			_isLeft = isLeft;
		}

		public ReColorId ReColorId => _isLeft ? _individualReferences.LeftReColorId : _individualReferences.RightReColorId;

		public MaterialDescription TargetMaterialDescription => _isLeft ? _references.LeftMaterialDescription : _references.RightMaterialDescription;

		public Texture2D Grayscale => _texture;

		public Texture2D Mask => null;

		public string name => _texture.name;

		public bool Sortable => false;

		public TargetMaterialTexture TargetMaterialTexture => _individualReferences.TargetMaterialTexture;

		public IEnumerable<MeshTag> MaskedMeshTags => Enumerable.Empty<MeshTag>();
	}
}
