using UnityEngine;


namespace CharacterCompositor
{
	/// <summary>
	/// Instance of IMixTexture generated by the scriptable object: EyeMixTextures
	/// </summary>
	class EyeMixTexture : IMixTexture
	{
		private readonly EyeMixTextures _textures;
		private readonly EyeMixTextureReferences _references;
		private readonly bool _isLeft;

		public EyeMixTexture(EyeMixTextures textures, EyeMixTextureReferences references, bool isLeft)
		{
			_textures = textures;
			_references = references;
			_isLeft = isLeft;
		}

		public ColorGroup DefaultColorGroup => _references.DefaultColorGroup;

		public Color ContrastMidpointColor => _textures.ContrastMidpointColor;

		public MaterialDescription TargetMaterialDescription => _isLeft ? _references.LeftMaterialDescription : _references.RightMaterialDescription;

		public Texture2D Shading => _textures.Fill;

		public Texture2D Mask => null;

		public string name => $"{_textures.name}_{_isLeft}";

		public bool Sortable => false;
    }
}
